In [1]:
import numpy as np

In [18]:
# define the environment and agent paramters
num_of_col = 5
num_of_row = 4
num_of_element = num_of_col * num_of_row
regular_reward_value = 0
goal_reward_value = 100
goal_col_index = 5
goal_row_index = 4
start_col_index = 1
start_row_index = 1

gamma = 0.9 # discount rate

In [22]:
# Generate the reward matrix in the grid
# Grid position (i, j) is (col, row), 1-based index, start from (1, 1)
# The state index is computed by the formula: 
# index = (j - 1) * num_of_columns + (i - 1) with (i, j) represent ith column and jth row in the grid
# Example:
# Grid environment with four rows and five column
# Goal state is at (5, 4) whose state index is (4-1)*5 + (5 - 1) = 19
# Start state is at (1,1) whose state index is (1-1)*5 + (1 - 1) = 0

class GridStateMatrix:
    def __init__(self, num_of_col, num_of_row, default_value=0):
        self.num_of_col = num_of_col # number of columns of the grid environment (position)
        self.num_of_row = num_of_row # number of rows of the grid environment (position)
        self.num_of_state = self.num_of_col * self.num_of_row # number of states in the state-action matrix
        self.default_value = default_value # default value for initial matrix
        matrixValues = [self.default_value for _ in range(self.num_of_state * self.num_of_state)]
        self.gridStateMatrix = np.matrix(matrixValues).reshape((self.num_of_state, self.num_of_state))
        
    def get_state_index(self, col_index, row_index):
        return (row_index - 1) * num_of_col + (col_index - 1)
    
    def get_grid_position(self, state_index):
        if (state_index >= self.num_of_state):
            return -1, -1
        row_index = state_index // self.num_of_col + 1
        col_index = state_index % self.num_of_col + 1
        return row_index, col_index
    
    def get_neighbors(self, col_index, row_index):
        neighbors = list()
        if (row_index < self.num_of_row): # up
            neighbors.append((col_index, row_index+1))
        if (row_index > 1): # down
            neighbors.append((col_index, row_index-1))
        if (col_index > 1): # left
            neighbors.append((col_index-1, row_index))
        if (col_index < self.num_of_col): # right
            neighbors.append((col_index+1, row_index))
        return neighbors
    
    def set_element_value(self, value, state_index, action_index):
        if (state_index >= self.num_of_state):
            return False
        if (action_index >= self.num_of_state):
            return False
        self.gridStateMatrix[state_index, action_index] = value
        return True

    def get_state_matrix(self):
        return self.gridStateMatrix

In [24]:
Reward = GridStateMatrix(num_of_col,num_of_row, -1)

# set up state-action relation between neighbor grid cell
for col in range(num_of_col):
    for row in range(num_of_row):
        neighbors = Reward.get_neighbors(col+1, row+1)
        s_index = Reward.get_state_index(col+1, row+1)
        for i, j in neighbors:
            print col+1, row+1, '->', i, j
            a_index = Reward.get_state_index(i, j)
            Reward.set_element_value(regular_reward_value, s_index, a_index)

relations = Reward.get_neighbors(goal_col_index, goal_row_index)
a_index = Reward.get_state_index(goal_col_index, goal_row_index)
for i, j in relations:
    print i, j
    s_index = Reward.get_state_index(i,j)
    Reward.set_element_value(goal_reward_value, s_index, a_index)
Reward.set_element_value(goal_reward_value, a_index, a_index)
        
print Reward.get_state_matrix()

1 1 -> 1 2
1 1 -> 2 1
1 2 -> 1 3
1 2 -> 1 1
1 2 -> 2 2
1 3 -> 1 4
1 3 -> 1 2
1 3 -> 2 3
1 4 -> 1 3
1 4 -> 2 4
2 1 -> 2 2
2 1 -> 1 1
2 1 -> 3 1
2 2 -> 2 3
2 2 -> 2 1
2 2 -> 1 2
2 2 -> 3 2
2 3 -> 2 4
2 3 -> 2 2
2 3 -> 1 3
2 3 -> 3 3
2 4 -> 2 3
2 4 -> 1 4
2 4 -> 3 4
3 1 -> 3 2
3 1 -> 2 1
3 1 -> 4 1
3 2 -> 3 3
3 2 -> 3 1
3 2 -> 2 2
3 2 -> 4 2
3 3 -> 3 4
3 3 -> 3 2
3 3 -> 2 3
3 3 -> 4 3
3 4 -> 3 3
3 4 -> 2 4
3 4 -> 4 4
4 1 -> 4 2
4 1 -> 3 1
4 1 -> 5 1
4 2 -> 4 3
4 2 -> 4 1
4 2 -> 3 2
4 2 -> 5 2
4 3 -> 4 4
4 3 -> 4 2
4 3 -> 3 3
4 3 -> 5 3
4 4 -> 4 3
4 4 -> 3 4
4 4 -> 5 4
5 1 -> 5 2
5 1 -> 4 1
5 2 -> 5 3
5 2 -> 5 1
5 2 -> 4 2
5 3 -> 5 4
5 3 -> 5 2
5 3 -> 4 3
5 4 -> 5 3
5 4 -> 4 4
5 3
4 4
[[ -1   0  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1]
 [  0  -1   0  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1]
 [ -1   0  -1   0  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1]
 [ -1  -1   0  -1   0  -1  -1  -1   0  -1  -1  -1  -1  

In [28]:
# initialize Q matrix
Q_current = GridStateMatrix(num_of_col, num_of_row)
#Q_prev = GridStateMatrix(num_of_col, num_of_row, 100)
print Q_current.get_state_matrix()

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [30]:
# initialize learning parameters
alpha = 1.0 # learning rate
epsilon = 0.1 # explore probability threshold
total_episode = 100 # total number of training episodes
#deltaQ = Q_current.get_state_matrix() - Q_prev.get_state_matrix()
#diffQ = np.asarray(deltaQ)*np.asarray(deltaQ)
#print diffQ

In [ ]:
# Repeat learning over episodes
episode = 0
while (episode < total_episode):
    # Initialize the state at start state
    
    # Check if current state is goal state
    
        # Choose action from s using policy derived from Q (epsilon-greedy)
        
        # Take action a, observe r and s'
        
        # update Q(s,a) <- Q(s,a) + alpha * [r + gamma*max_a' Q(s', a') - Q(s,a)]
        
        # move to next state s <- s' 