In [1]:
import numpy as np
import random as rnd

In [2]:
# define the environment and agent paramters
num_of_col = 5
num_of_row = 4
num_of_element = num_of_col * num_of_row
regular_reward_value = 0
goal_reward_value = 100
goal_col_index = 5
goal_row_index = 4
start_col_index = 1
start_row_index = 1

gamma = 0.9 # discount rate

In [4]:
# Reward matrix 
reward_matrix_values = [0 for _ in range(num_of_col*num_of_row)]
reward_matrix = np.matrix(reward_matrix_values).reshape((num_of_row, num_of_col))
reward_matrix[goal_row_index-1, goal_col_index-1] = goal_reward_value
print reward_matrix

[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 100]]


In [6]:
# state value matrix
# initialize V
V_values = [0 for _ in range(num_of_col*num_of_row)]
V_matrix = np.matrix(V_values).reshape((num_of_row, num_of_col))
print V_matrix

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
# initialize learning parameters
alpha = 1.0 # learning rate
epsilon = 0.0 # explore probability threshold
total_episode = 10000 # total number of training episodes